FROM mcr.microsoft.com/mssql/server:2022-latest

# Aceitar os termos da licença
ENV ACCEPT_EULA=Y

# Senha forte para o usuário sa
ENV SA_PASSWORD=TargetComex2025!

# Edição Developer (gratuita para dev/teste)
ENV MSSQL_PID=Developer